Lab9/config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

Lab9/portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('home/', views.index_view, name="home")
]

Lab9/portfolio/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    github_link = models.URLField()
    pythonanywhere_link = models.URLField()

    def __str__(self):
        return self.user.username


class Blog(models.Model):
    account = models.OneToOneField(Account, null=False, on_delete=models.CASCADE)
    areas = models.ManyToManyField('Area', related_name='blogs')

    def __str__(self):
        return f"Blog of {self.account.user.username}"


class Area(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=100)
    areas = models.ManyToManyField(Area, related_name='areas')

    def __str__(self):
        return self.name


class Post(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(upload_to='portfolio/', null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    authors = models.ManyToManyField(Author, related_name='posts')

    def __str__(self):
        return self.title


class Comment(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.title


class Like(models.Model):
    likes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')

    def __str__(self):
        return f"Post {self.post.title} has {self.likes} likes"

Lab9/portfolio/views.py
from django.shortcuts import render
import datetime


# Create your views here.
def home_page_view(request):
    return render(request, 'portfolio/home.html')


def index_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/home.html', context)

Lab9/portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block main %}

    <h3>Introdução</h3>
    <p>Aplicações web criativas por perfeccionistas com deadlines!</p>

    <p>Lista de topicos que falaremos:</p>
    <ul>
        {% for topico in topicos %}
        <li> {{ topico }} </li>
        {% endfor %}
    </ul>

    {% load static %}
    <img src="{% static 'portfolio/images/image.jpg' %}">

    {% if hora > 12 %}
        Boa tarde,
    {% else %}
        Bom dia,
    {% endif %}
    estamos em {{ local }}, e são {{ hora }} horas. </p>


{% endblock %}

Lab9/portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
    <meta name="author" content="Rui Mao">
    <meta name="description" content="Portfolio">
    <meta name="keywords" content="palavras chave">
	  <title >RUI MAO</title>
    <link rel="icon" href="{% static 'portfolio/images/image.jpg' %}" type="image/x-icon" sizes="196x196"/>
</head>

<style>
   
</style>

<body>
    <header>
      <div>Rui Mao</div>
      <nav>
        <a href="{% url 'portfolio:home' %}">home</a>      
        <a href="">products</a>      
        <a href="">about</a>      
        <a href="">contact</a>      
      </nav>
    </header>
    
    <main>
        {% block main %}
        {% endblock main %}
    </main>
    
    <footer>ULHT, 2023</footer>
  </body>  